### ISSUE TITLE
About Python Library Support

### ISSUE THREAD

**Issue by IcingTomato** [Sensirion/raspberry-pi-i2c-sen5x#1]
I saw this library last week. It seems only support C.

**Comment by psachs** [comment]
Hi @IcingTomato 

The python library is still under development, but should be released soon

**Comment by IcingTomato** [comment]
Thank you very much! ;-)

**Comment by psachs** [comment]
Hi @IcingTomato 

We could finally publish the Python driver. Please find the code here:
https://github.com/Sensirion/python-i2c-sen5x
