### ISSUE TITLE
Please contribute a driver to the Linux kernel

### ISSUE THREAD

**Issue by jadonk** [Sensirion/raspberry-pi-i2c-sen5x#2]
Userspace hacks like this are very frustrating for professional developers. Please do the *right* thing and contribute a driver to the Linux kernel itself.

**Comment by psachs** [comment]
thank you for you input. We are well aware of the difference between user space and kernel drivers.
We however recommend to use our drivers from user space and don't consider this as a hack.
Of course we are also very happy if our sensors are supported in the linux kernel. Currently we however don't have any plans to develop kernel drivers our self.
