### ISSUE TITLE
process outputs nan after a while

### ISSUE THREAD

**Issue by PickleRiiiick** [Sensirion/raspberry-pi-i2c-sen5x#3]
I changed sen5x_i2c_example_usage.c so it generates one output per minute for several hours. After 80 to 100 minutes it always starts to output only "nan".
If I start a second process in a second terminal in parallel it will sometimes start to output values again in both processes (probably due to the device_reset) or it will return errors regarding device_reset, reading_product_name, etc.
Any idea why this happens?

**Comment by psachs** [comment]
This could be caused by a brown out event due to insufficient or unstable power supply.

measurement mode has then to be started again to get sensor values `sen5x_start_measurement();`

Any other command (device reset, read product name) does not have any effect if the device reboots unexpectedly.

**Comment by PickleRiiiick** [comment]
Would an extra power supply for the sensor help? Does Sensirion provide any power supplies for their sensors?

**Comment by psachs** [comment]
Hi @PickleRiiiick 

Yes an external power supply could help. So far we never had the problem with connecting the Raspberry pi to a computer or using an external power supply for a Raspberry Pi.
It could also be an issue if you use a jumper cable that does not have a good connection. It therefore makes sense to check if all the connections are working well.
