### ISSUE TITLE
Merge Raspberry Pi and Generic Embedded Sen5x I2C repos

### ISSUE THREAD

**Issue by handledexception** [Sensirion/raspberry-pi-i2c-sen5x#4]
Is there a particular reason why there is a separation between this Raspberry Pi code base and the Generic Embedded (https://github.com/Sensirion/embedded-i2c-sen5x) code base for SEN5x? Both repos have what appear to be the same common code, with a hardware abstraction layer, and implementations for each platform. Why not just have a single repo with back-ends for RPi and embedded devices?

**Comment by sdmueller** [comment]
Hi @handledexception 

You are right, the code base is very similar.
The main reason we have them separated is that we want to provide an out-of-the-box experience for Raspberry Pi users where nothing has to be changed to make it work (including an easy to follow Readme with the wiring instructions etc.).

Hope this answers your question!
