### ISSUE TITLE
Error Running Testing Protocol

### ISSUE THREAD

**Issue by gflambesis** [Sensirion/raspberry-pi-i2c-sen5x#5]
I encountered an error when running cd ./sen5x_i2c_example_usage . When it ran, it gave errors in executing all functions saying (for example) "Error executing sen5x_device_reset(): -1". What can be done to fix this error? Thanks!

**Comment by LeonieFierz** [comment]
Hello,
can you please give us more details about your setup? Please check again that your wiring is correct, especially that you have the SDA and SCL connected correctly and you have your Rapsberry Pi powerd with an external power supply.
Best, Léonie

**Comment by gflambesis** [comment]
Hello, 
I changed the wire connecting the RPi and the Sen5x and it worked properly. Sorry for the waste of time. Thank you for helping.
