### ISSUE TITLE
Go or Rust library support

### ISSUE THREAD

**Issue by madpipeline** [Sensirion/raspberry-pi-i2c-sen5x#9]
Any plans for creating a Go library from this driver? How about for Rust?

**Comment by madpipeline** [comment]
A project already exists for Go: https://github.com/aggellos2001/sen5x-go

**Comment by quentin-cy** [comment]
Hello @madpipeline 
Nothing in that direction planned for now unfortunately.

Cheers
Q

**Comment by madpipeline** [comment]
Would you accept a PR in that direction?

**Comment by quentin-cy** [comment]
Hej @madpipeline 
 
 At first glance, I would say that it would not belong here.
 Our raspberry-pi drivers are always C drivers (that are themselves a derivative of our embedded drivers).
 A dedicated repository for a GO or Rust driver would make more sense.
 
 On that topic our [I2C Rust repository](https://github.com/Sensirion/sensirion-i2c-rs) might give you a headstart.
 Unfortunately we have nothing in GO for now.
 
 
 Cheers
 Q
